# Generated by Django 2.0 on 2018-01-04 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team', models.IntegerField()),
                ('classification', models.CharField(choices=[('ts', 'T-Shirt'), ('hat', 'Hat')], max_length=10)),
                ('description', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OneshirtUser',
            fields=[
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fname', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('team', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('a', 'Accepted'), ('d', 'Denied'), ('p', 'Pending')], default='p', max_length=10)),
                ('give', models.ManyToManyField(related_name='trade_item_given', to='trade.Item')),
                ('take', models.ManyToManyField(related_name='trade_item_gotten', to='trade.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.OneshirtUser'),
        ),
    ]
