# Generated by Django 2.0 on 2018-01-31 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import trade.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.PositiveIntegerField(default=trade.models.Item.generate_id, editable=False, primary_key=True, serialize=False)),
                ('team', models.IntegerField()),
                ('year', models.IntegerField(blank=True, null=True)),
                ('classification', models.CharField(
                    choices=[('ts', 'T-Shirt'), ('hat', 'Hat'), ('zip', 'Zip-Up Hoodie'), ('pull', 'Pullover Hoodie'),
                             ('swt', 'Sweater'), ('pnt', 'Pants'), ('sk', 'Socks'), ('etc', 'Doodad/Other')],
                    max_length=10)),
                ('description', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OneshirtUser',
            fields=[
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fname', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('team', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status',
                 models.CharField(choices=[('a', 'Accepted'), ('d', 'Denied'), ('p', 'Pending'), ('c', 'Cancelled')],
                                  default='p', max_length=10)),
                ('give', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_item_given',
                                           to='trade.Item')),
                ('recipient',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_user_recipient',
                                   to='trade.OneshirtUser')),
                ('requester',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_user_requester',
                                   to='trade.OneshirtUser')),
                ('take',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_item_gotten',
                                   to='trade.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.OneshirtUser'),
        ),
    ]
