# Generated by Django 2.0 on 2018-02-23 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trade', '0002_auto_20180207_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneshirtuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='trade.FRCTeam'),
        ),
    ]
