# Generated by Django 2.0 on 2018-02-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20180223_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
