# Generated by Django 2.0 on 2018-03-02 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_item_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('key', models.CharField(default=b'd0b0eb7e4cb6c9d2b0f730a0de8590', max_length=30, primary_key=True, serialize=False)),
                ('valid', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.OneshirtUser')),
            ],
        ),
    ]
