# Generated by Django 2.0 on 2018-03-12 16:43

from django.db import migrations, models

import trade.models


class Migration(migrations.Migration):
    dependencies = [
        ('trade', '0005_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='key',
            field=models.CharField(default=trade.models.PasswordResetRequest.gen_key, max_length=30, primary_key=True,
                                   serialize=False),
        ),
    ]
